version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-message-api-dev
    command: yarn start:dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # - DEBUG=1 (adicione variáveis extras se quiser)
    env_file:
      - .env
